### ISSUE TITLE
Python 3.6

### ISSUE THREAD

**Issue by jeffcjohnson** [scrapy-plugins/scrapy-djangoitem#18]
I'm trying to use DjangoItem in a Python 3.6 project and get the following error upon import:

`TypeError: __class__ set to <class 'scrapy_djangoitem.DjangoItem'> defining 'DjangoItem' as <class 'scrapy_djangoitem.DjangoItem'>
`

To reproduce if you have Python 3.6 is extremely simple:

```bash
python3 -m venv test_env
source ./test_env/bin/activate
pip install scrapy django scrapy-djangoitem
python -c "import scrapy_djangoitem"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../test/test_env/lib/python3.6/site-packages/scrapy_djangoitem/__init__.py", line 24, in <module>
    class DjangoItem(with_metaclass(DjangoItemMeta, Item)):
TypeError: __class__ set to <class 'scrapy_djangoitem.DjangoItem'> defining 'DjangoItem' as <class 'scrapy_djangoitem.DjangoItem'>
```

I would love to provide a pull request but this is a bit beyond my understanding.

**Comment by redapple** [comment]
hi @jeffcjohnson , thank you for reporting!
Indeed, there's an issue with Python 3.6: see this (test) Travis build: https://travis-ci.org/scrapy-plugins/scrapy-djangoitem/jobs/194757109
I'm not familiar with scrapy_djangoitem so it may take some time.
If someone from the community wants to jump in, they're more than welcome to do so.

**Comment by jeffcjohnson** [comment]
I ran into the same exception while using Scrapy's Item and trying to use inheritance.  This issue may be better in the Scrapy project.

```python items.
from scrapy import Item, Field


class BaseItem(Item):
    def clean(self):
        pass


class SpecialItem(BaseItem):
    def clean(self):
        super().clean()


if __name__ == '__main__':
    item = SpecialItem()
    item.clean()
```

```bash
python items_test.py
Traceback (most recent call last):
<snip>
    class SpecialItem(BaseItem):
TypeError: __class__ set to <class '__main__.SpecialItem'> defining 'SpecialItem' as <class '__main__.SpecialItem'>
```

**Comment by redapple** [comment]
@jeffcjohnson , Scrapy 1.3.1 has been released.
Could you check if upgrading solves your issue with scrapy-djangoitem?

**Comment by jeffcjohnson** [comment]
@redapple Sorry I didn't get back to this sooner.  I just ran the test from the top of this ticket and with the latest Scrapy (1.3.3) it worked fine.

Thanks!
