### ISSUE TITLE
Bump version to 1.0

### ISSUE THREAD

**Issue by pablohoffman** [scrapy-plugins/scrapy-djangoitem#4]
I think version `0.1.0` is unfair. This project has been used in production by a few users, and it's also classified as "Production/stable" quality (in `setup.py`), which is is not consistent with the 0.1.0 version.

Shall we bump it to 1.0 so? /cc @Curita @kmike

**Comment by curita** [comment]
I agree, I copied that convention from other scrapy projects (and scrapy itself) but this project should be already at `1.0`.

**Comment by pablohoffman** [comment]
Cool, can you make the change @Curita and push the new version for pypi?

**Comment by curita** [comment]
Done it, and the new version is uploaded to pypi. I had to force a commit because of a mistake I made before with .travis.yml, sorry for that.
